services:
  db_books:
    image: postgres:latest
    container_name: db_books_container
    environment:
      POSTGRES_DB: books
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_books_data:/var/lib/postgresql/data

volumes:
  postgres_books_data:
